name: "♻️ Deploy to Development Namespace"

on:
  workflow_dispatch:
  push:
    branches: [main]
env:
  # A majority of the secrets generated here come from the cloud-platform-environments repository.
  KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
  KUBE_NAMESPACE: ${{ secrets.DEV_KUBE_NAMESPACE }}
  KUBE_CERT: ${{ secrets.DEV_KUBE_CERT }}
  KUBE_TOKEN: ${{ secrets.DEV_KUBE_TOKEN }}

  IMAGE_TAG: ${{ github.sha }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_URL }}
  ECR_REPOSITORY: ${{ vars.DEV_ECR_REPOSITORY }}
  FLASK_APP_SECRET: ${{ secrets.DEV_FLASK_APP_SECRET }}

  POSTGRES_USER: ${{secrets.DEV_POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{secrets.DEV_POSTGRES_PASSWORD}}
  POSTGRES_DB: ${{secrets.DEV_POSTGRES_DB}}
  POSTGRES_HOST: ${{secrets.DEV_POSTGRES_HOST}}
  POSTGRES_PORT: ${{secrets.DEV_POSTGRES_PORT}}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
          aws-region: "eu-west-2"

      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        id: login-ecr
      - run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-dev:
    needs: build-push
    runs-on: ubuntu-latest
    container: alpine/k8s:1.23.17
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to the cluster
        run: |
          echo "${KUBE_CERT}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config get-contexts
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Deploy helm chart to dev
        run: |
          helm upgrade acronyms-app\
            helm/acronyms-app \
            --install \
            --force \
            --wait \
            --timeout 10m \
            --namespace ${KUBE_NAMESPACE} \
            --values=helm/acronyms-app/values-dev.yaml \
            --set app.deployment.env.APP_SECRET_KEY=${FLASK_APP_SECRET} \
            --set app.deployment.env.POSTGRES_USER=${POSTGRES_USER} \
            --set app.deployment.env.POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
            --set app.deployment.env.POSTGRES_DB=${POSTGRES_DB} \
            --set app.deployment.env.POSTGRES_HOST=${POSTGRES_HOST} \
            --set app.deployment.env.POSTGRES_PORT=${POSTGRES_PORT} \
            --set app.deployment.image.repository=${ECR_REGISTRY}/${ECR_REPOSITORY} \
            --set app.deployment.image.tag=${IMAGE_TAG}
